### PR TITLE
feat(knowledge): @repo/knowledge data layer (Plan 1 — knowledge hub foundation)

### PR DESCRIPTION
**Pull request by Kheirah**
## Summary

New source-only workspace package `@repo/knowledge` — the fully-tested MongoDB data layer for the knowledge hub (Plan 1 of 4). Mirrors `@repo/database` conventions; consumed by the upcoming ingestion backend (Plan 2), web surfaces (Plan 3), and ask-agent (Plan 4).

- **Schemas (Zod v4, single source of truth):** organizations, people, engagements, sources (voice/email/manual, incl. attachments), facts (≥1 anchor invariant, lifecycle convention: valid iff `validUntil` & `supersededBy` absent — exported as `currentlyValidFilter`), proposals (entity + fact drafts with pending/confirmed/edited/discarded resolutions)
- **Typed collections + idempotent indexes:** `getCollections(db)`, `ensureIndexes(db)`; every compound index leads with `tenantId`; unique gmail-message dedup via `partialFilterExpression`
- **GDPR Art. 17 erasure cascade:** `erasePerson` deletes person-anchored facts, redacts identifiers (full name, emails, and word-bounded name tokens incl. German genitive — Unicode-aware, since ASCII `\b` never fires before umlauts) in source texts *and* the proposal audit trail (open + resolved), discards pending drafts while leaving reviewed drafts' history intact, persists `blobsPendingDeletion` on orphaned-blob sources, and reports `orphanedBlobUrls` (audio + attachments) for caller-side deletion
- **Review write path:** `resolveProposalItems` — the single choke point that turns drafts into knowledge: strict-schema entity materialization, draft-anchor resolution (`organizationDraftId` → created entity), per-item confirm/edit/discard, proposal auto-resolve + source `reviewed`, idempotent re-run via deterministic `_id`s (crash-safe without transactions)
- **Search:** `facts_search` (with a `lucene.german` multi on `text`) + `organizations_search`/`people_search` for the resolve-context step and dedupe suggestions (3 indexes = exactly the M0 limit); pipeline builders for both; idempotent `setup-indexes` script with narrowed error handling
- **Runtime-portable entry points:** the barrel no longer transitively imports `server-only` (which throws in every non-react-server runtime — decisively, the Plan-2 eve app; reproduced from Bun tests). DB bootstrapping lives behind `@repo/knowledge/client` (house style, cf. `@repo/auth/server`) with an explicit browser guard and a configured client: `ignoreUndefined` (spreads with `undefined` lifecycle keys must not store BSON `null`), serverless pool/timeout right-sizing, `appName`

## Verification

- 52 pass / 0 fail with `MONGODB_TEST_URI` (local mongo:8); clean skip + exit 0 without it
- `turbo test typecheck --filter=@repo/knowledge` green; `bunx biome check packages/knowledge` 0 errors
- Brought current with `main` 2026-07-31 (merge; `biome.jsonc`/`bun.lock` conflicts resolved to main's side — main had applied the identical ultracite fixes independently — lockfile regenerated)

## Platform research notes (verified 2026-07-31)

- **Atlas automated embedding**: public preview; inference runs on MongoDB's multi-tenant service in **Google Cloud, US region, regardless of cluster region** → the spec's rejection stands. Embeddings stay deferred; the EU path when needed remains Mistral embed or self-deployed Voyage (SageMaker `eu-central-1`).
- **`$rankFusion`** is GA but needs MongoDB 8.1+ (M0/Flex pinned to 8.0); the query builders are fusion-ready if/when embeddings arrive on an M10+.
- **eve ≥0.27** documents direct AI SDK `LanguageModel` instances (incl. Bedrock `eu-central-1` with prompt caching) → the Plan-4 spike is resolved affirmatively from docs.
- **Workflow DevKit 4.x stores run state in `iad1`** → Plan-2 pipeline steps must pass ObjectIds, not transcript/email content (or adopt `workflow@5.0.0-beta.33+` for `fra1` state).

## Deferred / open items

- Spike A (AssemblyAI EU smoke test) still blocked on credentials + a voice memo — gates Plan 2's transcription request shape
- Source discriminated-union modeling remains a fast-follow
- `resolveProposalItems` v1: engagement drafts must carry a resolved `organizationId` (anchoring engagements to sibling org drafts errors clearly — extend when the extractor needs it)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Kheirah** [comment]
### Code review

Reviewed the branch as of 26327a7 (five parallel reviewers + confidence scoring). Found 3 issues, all addressed on this branch:

1. Erasure force-discarded already-reviewed proposal drafts: the `arrayFilters` matched every draft anchored to the erased person, so a draft a reviewer had confirmed in a still-open proposal was rewritten to `discarded` with a dangling `factId` — audit-trail falsification, reproduced against live MongoDB. Fixed in a74cac9 by scoping to `resolution.status: "pending"` (+ regression test).

https://github.com/hasToggle/hasToggle.dev/blob/26327a742e51cc959ab727e1d1785e6843643f25/packages/knowledge/erasure.ts#L42-L47

2. The package barrel re-exported `getKnowledgeDb` from `client.ts`, whose `server-only` import throws in every runtime that is not a react-server bundle — importing the canonical entry from a Bun test crashes (reproduced), and the package's primary future consumer (`apps/agent`, eve) is exactly such a runtime. Fixed in c33ebdd: DB bootstrapping moved behind `@repo/knowledge/client` with an explicit browser guard; barrel re-exports `ObjectId`.

https://github.com/hasToggle/hasToggle.dev/blob/26327a742e51cc959ab727e1d1785e6843643f25/packages/knowledge/index.ts#L2-L4

3. Latent `undefined`→BSON-`null` asymmetry: the client used driver defaults (`ignoreUndefined: false`), so spreading a typed object with absent lifecycle fields would store `null` — which `factSchema`'s `.optional()` fields reject on re-parse, breaking the documented "valid iff both absent" convention for any future write path. Fixed in c33ebdd via `ignoreUndefined: true` (+ behavioral test).

https://github.com/hasToggle/hasToggle.dev/blob/26327a742e51cc959ab727e1d1785e6843643f25/packages/knowledge/client.ts#L10-L17

Also cleaned up: a dead `pattern.lastIndex = 0` reset whose justifying comment described an impossible failure mode (the erasure rewrite in 75b352c removes the stateful `.test()` entirely).

🤖 Generated with [Claude Code](https://claude.ai/code)

<sub>- If this code review was useful, please react with 👍. Otherwise, react with 👎.</sub>
